# Generated by Django 5.1.1 on 2024-10-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.IntegerField(choices=[(1, 'Peserta'), (2, 'Admin Lomba')])),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('fakultas', models.CharField(max_length=255)),
                ('keterangan', models.TextField()),
                ('lokasi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Penyelenggara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_ponsel', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jenis_lomba', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('lokasi', models.CharField(max_length=255)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('no_hp', models.CharField(max_length=13)),
                ('alamat', models.CharField(max_length=255)),
                ('lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba')),
            ],
        ),
    ]
